# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dhruv Dhruv Revolution
realname: Dhruv Mittal
email: dhruvmittal@outlook.com
description: > # this means to ignore newlines until "baseurl:"
        So I have a website now. I had one once and I have one again. Tremble before me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "dhruvmittal.github.io" # the base hostname & protocol for your site
twitter_username: gnuslashdhruv
github_username:  dhruvmittal

# Build settings
markdown: kramdown
